# Site settings
repository: enuno/DynamicCareerCanvas
favicon: images/favicon.ico

version: 2

darkmode: true

# Personal info
name: Elvis Nuno
title: Chief Technology Solutions Architect & Blockchain/Web3/DePIN Evangel
email: enuno@proton.me
phone: +1 (406) 519-9696
website: https://keybase.io/elvisnuno
# Social links
twitter_username: NunoElvis
github_username:  enuno
linkedin_username: elvis-nuno-5635914
orcid_username: 0009-0002-8601-0527
# pinterest_username:
# youtube_username:
# dribbble_username:
# facebook_username:
# flickr_username:


# About Section
about_title: About Me
about:
about_profile_image: images/profile_image.jpg
about_content: |
  As a dynamic and innovative technology solutions architect, experienced systems engineer, and Blockchain, Web3, and DePIN evangelist, I specialize in helping professionals and organizations navigate their evolving technological journeys. With 20 years of hands-on experience in building and optimizing ISP and telecom infrastructure, I blend strategic insights with advanced tools to improve business operations and empower individuals in shaping their career paths with clarity and confidence. My expertise is largly focused in designing technical and organizational frameworks that enable sustainable growth, future-focused development, and the strategic adoption of decentralized technologies that demonstrate a strong value in practical real-world applications to improve and modernize critical infrastructure.

  With a strong emphasis on adaptability, I guide businesses, teams, and individuals in harnessing their potential and seizing opportunities in a rapidly changing technological landscape. I am passionate about working with technical teams in solving complex challenges in telecommunications, DevOps, cloud, and distributed systems engineering while advancing blockchain, DePIN, and Web3 technologies to foster a more connected, secure, and decentralized world. Whether architecting resilient networks or mentoring the next generation of engineers, I approach every task with enthusiasm and a commitment to excellence, empowering individuals to define their unique value, build highly successful teams, and leave lasting professional legacies.

content:
  - title: Skills
    layout: list
    content:
      - title: Networking
        description: |
         - OSI Model
         - Layer 2 Protocols: ARP, (R)STP, LLDP, LACP, 802.1Q/VLAN tagging
         - IP Protocols: TCP, UDP, ICMP
         - Routing Protocols: BGP, OSPF, VRRP
         - Layer 3 Protcols: DNS, SSL, SSH, SNMP, VPN (IPsec, OpenVPN, Wireguard)

      - title: Systems Engineering
        description: |
         - Linux/UNIX
         - Cloud Platforms (AWS, GCE, Azure, OpenStack)
         - Virtualization (KVM, Xen, VMware, Proxmox)
         - Containerization (Docker, LXC)
         - Configuration Management (Ansible, Puppet, Chef)

      - title: DevOps
        description: |
         - CI/CD Pipelines (Jenkins, Bamboo)
         - Infrastructure as Code (Terraform, CloudFormation)
         - Container Orchestration (Kubernetes)

      - title: Blockchain/Web3
        description: |
         - DePIN projects
         - dVPN (Sentinel, Mysterium)
         - dStorage (Filecoin, Storj, Sia, Arweave)
         - dCloud (Akash, Flux Network)
         - Mixnets (Nym, AnyOne Network)
         - DeWi (Helium, Althea, Nodle)
         - Cryptocurrency Mining (ASIC, GPU)
         - Automated Trading

      - title: Leadership
        description: |
         - Technical Mentoring
         - Cross-Departmental Collaboration
         - Strategic Planning
         - Project Management

  title: Publications, Presentations, and Projects
    layout: list
    content:
      - layout: top-middle
        border: weak
        title: Community ISP Handbook
        link: https://bsi-mt.notion.site/9391097364e84f33968423a0b0a7a230
        quote: >
          Authored and freely published an online guide to assist rural communities in forming local ISPs and constructing community-owned internet infrastructure.
      - layout: top-middle
        title: NymBox
        quote: >
          Developed software components for integrating the NYM mixnet privacy network into OpenWRT-based routers under a Nymtech grant-funded project.
        link: https://github.com/The-Pacific-NW-Rural-Broadband-Alliance/nymbox
      - layout: top-middle
        title: Bridging the Digital Divide
        quote: >
          Presented an overview of how the DePIN platform Althea could be applied to serve Mission Valley residents with a community-owned wireless ISP solution. Funded by a grant from the Mission Valley Community Development Partners.
        link: https://www.youtube.com/watch?v=D0J-QLv0ZHA
      - layout: top-middle
        title: Missoula Valley Internet Co-op Network Launch
        quote: >
          Featured on KPAX News for launching the Missoula Valley Internet Co-op network, providing broadband service to underserved areas in Missoula, MT.
        link: https://www.youtube.com/watch?v=FBwfHBQqZcs
      - layout: top-middle
        border: weak
        title: In Missoula, Montana, a Wireless Mesh Network Builds Community and Connections
        quote: >
          An article written by Ry Marcattilio, published by the Institue for Local Self-Reliance on December 14, 2021, covering the intial formation and development of the Missoula Valley Internet Co-op using Althea's DePIN wireless mesh-networking platform.
        link: https://communitynets.org/content/missoula-montana-wireless-mesh-network-builds-community-and-connections
      - layout: top-middle
        border: weak
        title: Montana Economic Developers Association Broadband Improvement Advisory Committee Member
        quote: >
          Served as a member of an advisory committee tasked with advising state representatives on standards and requirements for allocating federal funds under House Bill 632, which implemented the American Rescue Plan Act (ARPA). Our recommendations contributed to the drafting of Montana Senate Bill 297, which established the ConnectMT Act program to expand broadband infrastructure across the state.
        link: https://connectmt.mt.gov/General-Information/

  - title: Experience
    layout: list
    content:
      - layout: left
        border: weak
        title: Centric Internet Services
        sub_title: Director of Network Operations
        caption: January 2024 - August 2024
        description: |
         - Led the successful integration of two distinct ISP networks, ensuring seamless merging with minimal downtime.
         - Identified and addressed vulnerabilities within legacy infrastructure, enhancing network reliability and performance.
         - Developed and implemented future-proof solutions for core network infrastructure, advancing wireless ISP and decentralized DeWi technology.

      - layout: left
        border: weak
        title: Pacific NW Rural Broadband Alliance
        sub_title: President, Co-Founder, Head of Operations
        caption: November 2019 - January 2024
        description: |
          - Led engineering and deployment of community-owned ISPs in underserved rural communities in Montana.
          - Secured grants and community funds to deliver broadband-quality service to areas outside traditional ISP profit models.
          - Collaborated with DePIN projects like Althea, Nym, and Helium to deploy distributed internet, IoT connectivity, and privacy infrastructure.

      - layout: left
        border: weak
        title: SolluCIO
        sub_title: Linux System Engineer
        caption: July 2019 - November 2019
        description: |
          - Built a high-availability, cloud-based eCommerce platform, optimizing security and performance for a grocery store chain in Hawaii.

      - layout: left
        border: weak
        title: REW Consulting Services
        sub_title: Solutions Architect & Technical Consultant
        caption: June 2018 - February 2019
        description: |
          - Provided consulting on DevOps best practices, Ansible automation, and Jenkins CI/CD pipelines for telecom providers.

      - layout: left
        border: weak
        title: goMoxie
        sub_title: Lead DevOps Engineer - Cloud Services
        caption: June 2016 - December 2016
        description: |
          - Led a team to establish DevOps best practices and transitioned siloed teams to a unified model. Automated infrastructure on VMware and AWS.

      - layout: left
        border: weak
        title: McGraw-Hill Education
        sub_title: Senior DevOps Engineer
        caption: June 2015 - March 2016
        description: |
          - Managed pre-production environments and production deployments on AWS, supporting online educational courseware.
          - Developed CloudFormation scripts, Puppet modules, and Jenkins pipelines for automated software builds and deployments.

      - layout: left
        boarder: weak
        title: CDK Global
        sub_title: Senior Linux Systems Automations Engineer
        caption: October 2014 - June 2015
        description: |
          - Automated cloud provisioning and scaling with Puppet in a multi-datacenter environment; developed a distributed monitoring platform using Icinga.

      - layout: left
        boarder: weak
        title: CDK Global
        sub_title: Senior Linux Systems Automations Engineer
        caption: October 2014 - June 2015
        description: |
          - Automated cloud provisioning and scaling with Puppet in a multi-datacenter environment; developed a distributed monitoring platform using Icinga.

      - layout: left
        boarder: weak
        title: Salesforce
        sub_title: Senior Linux Systems Automations Engineer
        caption: Febuary 2014 - October 2014
        description: |
          - Managed a 500+ server environment on IBM SoftLayer for a PHP-based marketing and sales web application, utilizing Chef for configuration management, Bamboo for automated builds, and supporting rolling releases, while also engineering an OpenStack private cloud migration, managing large-scale MySQL master/master replication, and providing 24/7 on-call infrastructure support.

      - layout: left
        boarder: weak
        title: Clearwire (7 years)
        sub_title: DevOps Release Manager
        caption: October 2011 - October 2013
        description: |
          - Led deployments for high-traffic e-commerce sites and managed pre-production environments, migrating to VMware virtual servers.

      - title: Linux Systems Administrator
        sub_title: January 2010 - September 2011
        description: |
          - Administered 200+ Linux servers in a 24x7 environment, corporate Asterisk PBX phone systems, automated configurations with Puppet, and implemented Nagios monitoring.

      - title: IT Production Support Engineer
        sub_title: June 2008 - January 2010
        description: |
          - Supporting operations of web-based CRM systems for supported sales staff, managing geo-coding services, indirect dealer systems, and coordinating system-wide outage responses.

      - title: Network Operations Technician - Shift Lead
        sub_title: December 2006 - June 2008
        description: |
          - Shift lead for NOC operations for a nationwide OSI layer 2 WISP network, coordinating site provisioning and network outage repairs.

      - layout: left
        boarder: weak
        title: Logistic Systems, Inc.
        sub_title: Record Management Systems Engineer
        caption: June 2005 - October 2006
        description: |
          - Provided remote support for custom record management software and managed IBM AIX and Windows Server systems for municipal departments.

      - layout: left
        boarder: weak
        title: University of Montana
        sub_title: OS X Systems Administrator
        caption: June 2004 - August 2005
        description: |
          - Managed a computer lab and server environment for the universityâ€™s newspaper, supporting journalism students and upgrading the website backend.

footer_show_references: true
references_title: References on request

# Build settings
remote_theme: sproogen/modern-resume-theme
sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
